#!/bin/sh -e

case "$1" in
    configure)
        if [ "$(cat /sys/kernel/mm/ksm/run)" -ne "1" ]; then
            echo "!!! KSM not active !!!"
        fi

        if command -v systemctl >/dev/null 2>&1; then
            deb-systemd-invoke restart zabbix-agent.service || true
        elif command -v invoke-rc.d >/dev/null 2>&1; then
            invoke-rc.d zabbix-agent stop || true
            invoke-rc.d zabbix-agent start || true
        else
            /etc/init.d/zabbix-agent stop || true
            /etc/init.d/zabbix-agent start || true
        fi
    ;;
    abort-upgrade|abort-deconfigure|abort-remove)
    ;;
    *)
        echo "$0 called with unknown argument \`$1'" 1>&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
