#!/bin/sh -e

case "$1" in
    failed-upgrade|abort-install|abort-upgrade|disappear|upgrade)
    ;;
    remove|purge)
        if command -v zabbix-agentd >/dev/null 2>&1; then
            deb-systemd-invoke restart zabbix-agent.service || true
        elif command -v zabbix-agent2 >/dev/null 2>&1; then
            deb-systemd-invoke restart zabbix-agent2.service || true
        fi
    ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
