#!/bin/sh -e

case "$1" in
    configure)
        if [ "$(cat /sys/kernel/mm/ksm/run)" -ne "1" ]; then
            echo "!!! KSM not active !!!"
        fi

        if command -v zabbix-agentd >/dev/null 2>&1; then
            deb-systemd-invoke restart zabbix-agent.service || true
        elif command -v zabbix-agent2 >/dev/null 2>&1; then
            deb-systemd-invoke restart zabbix-agent2.service || true
        fi
    ;;
    abort-upgrade|abort-deconfigure|abort-remove)
    ;;
    *)
        echo "$0 called with unknown argument \`$1'" 1>&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
